var data = [
    {
        "title": "Looking at the Marshall CV506",
        "entry": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque et lacinia libero, sed tristique sapien. Nullam odio libero, eleifend eget odio efficitur, fringilla fermentum diam. Vestibulum consequat eget quam at varius. Suspendisse mollis dignissim ipsum, sit amet consectetur erat finibus vitae. Praesent tempus lorem ante, at tempor justo lacinia ac. Suspendisse convallis a nisi id finibus. Mauris pharetra justo ut neque rutrum, eget tristique ipsum maximus. In at mi a sapien faucibus blandit. Curabitur vel magna purus.",
        "date": "10/12/2019"
    },
    {
        "title": "Guys, You Won't Believe What Just Happened To Me!",
        "entry": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi porttitor leo mattis, luctus ipsum mattis, cursus nunc. In hac habitasse platea dictumst. Sed porta posuere condimentum. Integer fermentum justo augue, at egestas velit euismod in. Curabitur sed metus luctus, maximus dui et, sagittis mauris. Nunc risus lacus, egestas vel blandit et, sollicitudin venenatis purus. Integer in lacinia diam. In congue est nibh, sit amet aliquam elit ullamcorper sodales. Suspendisse potenti. Ut neque metus, tempor sit amet gravida in, vestibulum eget magna.",
        "date": "10/14/2019"
    },
    {
        "title": "Bootcamp, Day 2: JavaScript already!",
        "entry": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut eu felis eget dui ornare tincidunt in at turpis. Fusce consequat tellus varius mauris consectetur ultricies sed sed ex. Suspendisse placerat eros a libero aliquam finibus. Donec lacinia turpis eget dapibus feugiat. Vivamus in placerat risus. Phasellus luctus lobortis nisl, ut varius libero aliquet sed. Nunc tristique ante id fermentum rutrum. Pellentesque eu magna id diam accumsan fringilla in sed turpis. Aliquam dignissim et purus eu finibus. Donec porttitor neque nulla, sit amet aliquet mi tempor non. Vestibulum orci quam, porta vel pretium ac, lobortis porttitor quam. Aliquam ac neque et libero sollicitudin facilisis. Mauris non sem sed odio porta hendrerit. Quisque dignissim metus vulputate magna cursus consectetur. Quisque rhoncus sit amet justo vitae varius.",
        "date": "10/29/2019"
    },
    {
        "title": "Why Pokemon Is The Greatest Game",
        "entry": "Man was not always the dominant species on our planet: before us, dinosaurs claimed dominion. Pivotal times were those just as man discovered fire, surrounded by creatures physically superior to us. Danger and death were around every corner, yet Man’s mind and imagination flourished. Images and interactions with the dinosaurs fueled a new way of thinking. The Pokemon way of thinking. Through the trials and tribulations of our ancestors, Pokemon was conceived and has since became the great game of all time. Pokemon allows individuals to foster the growth mindset, teaches opportunity cost, and has become a truly timeless game. \nPokemon allows individuals to foster the growth mindset by allowing individuals to experience the joy of raising a Pokemon from levels such as 5, all the way to levels such as 100. Of note is that one has just as much fun battling level 5’s, as battling level 100s. Furthermore, individuals are allowed to repeatedly battle players or gyms until they defeat them. Between these two aspects, players of Pokemon begin to understand that growing is a part of life, and you can have just as much fun at level 5, as level 100, as long as you are progressing. \nPokemon teaches gamers opportunity cost by introducing restrictions into the game. A Pokemon can only have 4 moves. A Pokemon move generally cannot be re-learned once forgotten: the decisions you make are irrevocable. You may only choose 6 to come along with you at once, and you must find a way to utilize HM’s, potentially teaching a poorer move to a Pokemon just so you can utilize it. Through all these choices, there are consequences. The game then leads players to understand that their choices have ramifications. Choose wisely. \nPokemon has truly became a timeless game. Not only has every generation since the 90’s have a new game or few to themselves, but even the games from the 90’s have re-playability. Nothing is better than running through Pokemon during a long road trip. Furthermore, with the invention of smart phones and emulators, one can ALWAYS have Pokemon with them! I myself have an Emulator and Pokemon on my phone. It even includes the ability to speed up the game, making it even more enjoyable. Pokemon has unlimited playthroughs as well as teaches valuable skills relevant to any generation. To train, to be the best, to catch them all. These things any individual can relate to. Pokemon is truly a timeless game.\nIn conclusion, Pokemon is the greatest game of all time due to its fostering of the growth mindset, it teaching opportunity cost, and it being timeless. I urge you all to either download the GBA Emulator app (I am not affiliated with it) or a Pokemon game, or pick up a classic Gameboy (not affiliated). Introduce yourself to the wonder of Pokemon. Introduce yourself to the greatest game ever.",
        "date": "11/05/2019"
    }
];
